### PR TITLE
Use all variations when processing products

### LINKED ISSUE #11: Stock is not updated for out-of-stock products with specific store settings
The plugin uses `WC_Product_Variable::get_available_variations()` to determine the variations that need to be processed.

For instance, here:

https://github.com/PostiDigital/woocommerce-warehouse-plugin/blob/096177d65a6f0fcc9b4c84168fe4d47b115b06e3/classes/class-product.php#L459

However, when the store is set to hide out-of-stock products, [those products are ignored altogether](https://github.com/woocommerce/woocommerce/blob/bff253d6dc822f8051be440e585b4856f857f8e2/plugins/woocommerce/includes/class-wc-product-variable.php#L317-L320).
This causes the warehouse plugin to not update stock for these products. The products will be stuck in an out-of-stock state.

```php
public function get_available_variations( $return = 'array' ) {
    ...
    foreach ( $variation_ids as $variation_id ) {
        if ( ! $variation || ! $variation->exists() || ( 'yes' === get_option( 'woocommerce_hide_out_of_stock_items' ) && ! $variation->is_in_stock() ) ) {
            continue;
        }
    }
    ...
}
```

### PR DESCRIPTION
**Pull request by Saggre**
Closes #11

### CODE REVIEW

**Comment by Saggre** [comment]
Cloned `WC_Product_Variation::get_available_variations()`, but also:
- Removed hook `woocommerce_hide_invisible_variations`, because users may not intend to skip stock updates for variations even if they hide them
- Removed function param `$return` because another return type does not need to be supported

**Comment by Saggre** [comment]
Removed old commit from history, targeted `release/2.6.0`

**Review by suhhomi1 — APPROVED** [review]
This can be merged, some observations:
1. get_available_variations could return early by checking empty variation_ids.
2. Seems for loop would be more straightforward without negating condition.
3. New code seems to introduce new style by adding extra spaces.

**Comment by Saggre** [comment]
> This can be merged, some observations:
> 
> 1. get_available_variations could return early by checking empty variation_ids.
> 2. Seems for loop would be more straightforward without negating condition.
> 3. New code seems to introduce new style by adding extra spaces.

1. Added check
2. Removed negating condition
3. Migrated from WP code style to project code style. Used empty array assignment as `array()` and empty array return as `[]` because they also differed across the project

**Pull request merged**
